name: SOOS DAST GitHub Actions
on: [push]
jobs:
  synchronous-analysis-with-blocking-result-001:
    name: SOOS SCA Scan 001
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-041"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "php"
  synchronous-analysis-with-blocking-result-002:
    name: SOOS SCA Scan 002
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-042"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "npm"
  synchronous-analysis-with-blocking-result-003:
    name: SOOS SCA Scan 003
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-043"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "ruby"
  synchronous-analysis-with-blocking-result-004:
    name: SOOS SCA Scan 004
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-044"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "rust"
  synchronous-analysis-with-blocking-result-005:
    name: SOOS SCA Scan 005
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-045"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
  synchronous-analysis-with-blocking-result-006:
    name: SOOS SCA Scan 006
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-046"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "php"
  synchronous-analysis-with-blocking-result-007:
    name: SOOS SCA Scan 007
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-047"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "npm"
  synchronous-analysis-with-blocking-result-008:
    name: SOOS SCA Scan 008
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-048"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "rust"
  synchronous-analysis-with-blocking-result-009:
    name: SOOS SCA Scan 009
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-049"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        package_managers: "ruby"
  synchronous-analysis-with-blocking-result-010:
    name: SOOS SCA Scan 010
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.2.0
      with:
        project_name: "github-integration-sca-050"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
  soos_dast_baseline_analysis-001:
    name: SOOS DAST Baseline Analysis 001
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-041"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-002:
    name: SOOS DAST Baseline Analysis 002
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-042"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://www.hackthebox.eu/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-003:
    name: SOOS DAST Baseline Analysis 003
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-043"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://ctflearn.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-004:
    name: SOOS DAST Baseline Analysis 004
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-044"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "http://www.itsecgames.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-005:
    name: SOOS DAST Baseline Analysis 005
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-045"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://www.hackthissite.org/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-006:
    name: SOOS DAST Baseline Analysis 006
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-046"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-007:
    name: SOOS DAST Baseline Analysis 007
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-047"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-008:
    name: SOOS DAST Baseline Analysis 008
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-048"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-009:
    name: SOOS DAST Baseline Analysis 009
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-049"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
  soos_dast_baseline_analysis-010:
    name: SOOS DAST Baseline Analysis 010
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.3
        with:
           client_id: ${{ secrets.SOOS_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_API_KEY }}
           project_name: "github-integration-dast-050"
           api_url: "https://qa-api.soos.io/api/"
           scan_mode: "baseline"
           target_url: "https://brokencrystals.com/"
           output_format: "sarif"
           #on_failure: "continue_on_failure"
